---
- name: Deploy WAR to Tomcat container
  hosts: localhost
  connection: local
  vars:
    tomcat_webapps_path: /usr/local/tomcat/webapps
    tomcat_container_name: tomcat
    war_file: "{{ artifact }}"

  tasks:
    - name: Copy WAR to Tomcat webapps
      copy:
        src: "{{ war_file }}"
        dest: "{{ tomcat_webapps_path }}/ROOT.war"
        mode: '0644'

    - name: Restart Tomcat container
      community.docker.docker_container:
        name: "{{ tomcat_container_name }}"
        state: restarted
