- name: Deploy WAR to Tomcat container
  hosts: localhost
  connection: local
  become: true       # <<< run tasks as root
  vars:
    tomcat_webapps_path: /home/jenkins/tomcat/webapps
    tomcat_container_name: tomcat
    war_file: "../{{ artifact }}"

  tasks:
    - name: Ensure Tomcat webapps directory exists
      file:
        path: "{{ tomcat_webapps_path }}"
        state: directory
        mode: '0755'

    - name: Copy WAR to Tomcat webapps
      copy:
        src: "{{ war_file }}"
        dest: "{{ tomcat_webapps_path }}/ROOT.war"
        mode: '0644'

    - name: Restart Tomcat container
      community.docker.docker_container:
        name: "{{ tomcat_container_name }}"
        state: restarted


